#!/usr/bin/env python3
"""
build_nav.py — file-based navigation so an agent can browse the KB as a tree without a vector DB.

Generates, deterministically from talk frontmatter (stdlib only, offline):
  1. kb/series/<slug>.md  — every series page listing its talks, grouped by year.
  2. A regenerable "browse all talks" backlink block on each kb/topics/* and kb/entities/people/*
     page, between <!-- NAV:START --> / <!-- NAV:END --> markers (idempotent; safe to re-run).

Result: INDEX.md -> topic / series / person page -> the exact talks behind it -> the talk's
citations. Every hop is a [[wikilink]] an agent (or a human) can follow. Run after ingesting:
    python3 scripts/build_nav.py
"""
import os, re
from collections import defaultdict
from kblib import iter_pages

NAV_START = "<!-- NAV:START (generated by scripts/build_nav.py — edits inside are overwritten) -->"
NAV_END = "<!-- NAV:END -->"

SERIES_TITLES = {
    'startup-school': 'Startup School',
    'lightcone': 'The Lightcone Podcast',
    'how-to-start-a-startup': 'How to Start a Startup',
    'dalton-and-michael': 'Dalton & Michael',
    'talks': 'Talks & Interviews',
}


def load_talks():
    talks = []
    for path, fm, _ in iter_pages('kb/talks'):
        if fm.get('type') != 'yc-video':
            continue
        talks.append({
            'slug': fm.get('slug') or os.path.splitext(os.path.basename(path))[0],
            'title': fm.get('title', ''),
            'series': fm.get('series', 'talks'),
            'date': fm.get('upload_date', '') or '',
            'topics': fm.get('topics', []) or [],
            'speakers': fm.get('speakers', []) or [],
        })
    return talks


def inject_nav(path, block):
    with open(path, encoding='utf-8') as f:
        t = f.read()
    navtext = NAV_START + "\n" + block + "\n" + NAV_END
    if NAV_START in t and NAV_END in t:
        t = re.sub(re.escape(NAV_START) + r'.*?' + re.escape(NAV_END), lambda m: navtext, t, flags=re.S)
    else:
        t = t.rstrip() + "\n\n" + navtext + "\n"
    with open(path, 'w', encoding='utf-8') as f:
        f.write(t)


def talk_list(items):
    return "\n".join(f"- [[{tk['slug']}]] — {tk['title']}" for tk in items)


def main():
    talks = load_talks()

    # 1) series pages
    by_series = defaultdict(list)
    for tk in talks:
        by_series[tk['series']].append(tk)
    os.makedirs('kb/series', exist_ok=True)
    for series, items in by_series.items():
        title = SERIES_TITLES.get(series, series.replace('-', ' ').title())
        by_year = defaultdict(list)
        for tk in items:
            by_year[(tk['date'] or '????')[:4]].append(tk)
        lines = ["---", "type: series", f'title: "{title}"', f"slug: {series}",
                 "updated: 2026-07-05", "---", f"# {title}", "",
                 f"{len(items)} talks in the corpus, newest first. Follow any link below to open the talk page.", ""]
        for yr in sorted(by_year, reverse=True):
            lines.append(f"### {yr}")
            lines.append(talk_list(sorted(by_year[yr], key=lambda x: x['date'], reverse=True)))
            lines.append("")
        with open(f"kb/series/{series}.md", 'w', encoding='utf-8') as f:
            f.write("\n".join(lines).rstrip() + "\n")

    # 2) topic backlinks
    by_topic = defaultdict(list)
    for tk in talks:
        for tp in tk['topics']:
            by_topic[tp].append(tk)
    n_topics = 0
    for path, fm, _ in iter_pages('kb/topics'):
        slug = fm.get('slug') or os.path.splitext(os.path.basename(path))[0]
        items = sorted(by_topic.get(slug, []), key=lambda x: x['date'], reverse=True)
        if not items:
            continue
        inject_nav(path, f"## Browse all {len(items)} talks tagged `{slug}`\n\n" + talk_list(items))
        n_topics += 1

    # 3) person backlinks
    by_person = defaultdict(list)
    for tk in talks:
        for sp in tk['speakers']:
            by_person[sp].append(tk)
    n_people = 0
    for path, fm, _ in iter_pages('kb/entities/people'):
        slug = fm.get('slug') or os.path.splitext(os.path.basename(path))[0]
        items = sorted(by_person.get(slug, []), key=lambda x: x['date'], reverse=True)
        if not items:
            continue
        inject_nav(path, f"## Browse all {len(items)} talks featuring {fm.get('title', slug)}\n\n" + talk_list(items))
        n_people += 1

    print(f"Nav built: {len(by_series)} series pages, {n_topics} topics backlinked, {n_people} people backlinked "
          f"({len(talks)} talks indexed).")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
